### PR TITLE
Fix build of Yara on macOS

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by radare** [comment]
i've find out several problems in yara's configure, and hacking workarounds in node-yara side it just feels wrong.

Also, ther are several other problems here. the most important one is that you are building with -no-fexception and using throw, which results in a failure compilation, wondering why this should build on any system unless the c++ compiler is old.

I have some other complains but will try to fix them all in PRs for yara and node-yara.

Thanks for that module!

**Comment by stephenwvickers** [comment]
Nice one!

I'll take a look at this tomorrow night, merge and update the docs, and if all looks okay on my Mac then I'll publish a new build.

Thanks for the PR

Steve

**Comment by stephenwvickers** [comment]
Hi @radare 

FYI, there was an issue with the patch once merged (YARA_CFGOPTS vs CFGOPTS in the Makefile).

I've corrected these following merge.

Thanks

Steve

**Comment by stephenwvickers** [comment]
@radare Can you try installing on Mac from npm and see if it installs at works?

I had a little trouble with Mac OS versions, but it may be local.

Thanks

Steve

**Comment by radare** [comment]
works fine!

thanks!

**Comment by stephenwvickers** [comment]
Excellent, thanks.

There are few tweaks which can be done to support libmagic, and some requirements in terms of "brew install autoconf ..." etc, so I will open another issue to make those changes, then release a new build with "official" Mac OS support.

Many thanks for the work.

Steve

**Comment by radare** [comment]
Yeah there are several things to imrpove here. Also, upgrading to yara 3.6, now that it's out :)

Good work! Thanks for publishing this

**Comment by stephenwvickers** [comment]
No problem.

Out of interest, what do you plan to use the module for?

**Comment by radare** [comment]
At the moment just for experimenting and comparing times with other implementations. Just need to find some spare time and i'll let you know

**Comment by stephenwvickers** [comment]
Excellent, would love to hear how you found the performance.

Thanks

**Pull request merged**
